### PR TITLE
docs: add installation instruction for Nix

### PR DESCRIPTION
**Pull request by PerchunPak**
But https://github.com/NixOS/nixpkgs/pull/355870 is still not merged, so this won't do anything (yet)

### CODE REVIEW

**Comment by PerchunPak** [comment]
It will be available to users soon, so I think we can merge this
https://nixpk.gs/pr-tracker.html?pr=355870

**Comment by okineadev** [comment]
> It will be available to users soon, so I think we can merge this
> https://nixpk.gs/pr-tracker.html?pr=355870

Do this as an installation method using the <details> element

**Comment by okineadev** [comment]
It should be above the compatibility table

**Comment by okineadev** [comment]
It should be above the compatibility table

**Pull request merged**
